// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetMVP.Infrastructure.Persistence;

#nullable disable

namespace NetMVP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NetMVPDbContext))]
    partial class NetMVPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NetMVP.Domain.Entities.GenTable", b =>
                {
                    b.Property<long>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TableId"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("business_name");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("class_name");

                    b.Property<string>("CreateBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FunctionAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("function_author");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("function_name");

                    b.Property<string>("GenPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("gen_path");

                    b.Property<string>("GenType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("gen_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("module_name");

                    b.Property<string>("Options")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("options");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("package_name");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("SubTableFkName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sub_table_fk_name");

                    b.Property<string>("SubTableName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sub_table_name");

                    b.Property<string>("TableComment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("table_comment");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("table_name");

                    b.Property<string>("TplCategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tpl_category");

                    b.Property<string>("TplWebType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tpl_web_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TableId");

                    b.ToTable("gen_table");
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.GenTableColumn", b =>
                {
                    b.Property<long>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ColumnId"));

                    b.Property<string>("CSharpField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("csharp_field");

                    b.Property<string>("CSharpType")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("csharp_type");

                    b.Property<string>("ColumnComment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("column_comment");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("column_name");

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("column_type");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DictType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dict_type");

                    b.Property<string>("HtmlType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("html_type");

                    b.Property<string>("IsEdit")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_edit");

                    b.Property<string>("IsIncrement")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_increment");

                    b.Property<string>("IsInsert")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_insert");

                    b.Property<string>("IsList")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_list");

                    b.Property<string>("IsPk")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_pk");

                    b.Property<string>("IsQuery")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_query");

                    b.Property<string>("IsRequired")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_required");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("query_type");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("ColumnId");

                    b.ToTable("gen_table_column", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("config_name");

                    b.Property<string>("ConfigType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasColumnName("config_type");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("config_value");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("sys_config", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysDept", b =>
                {
                    b.Property<long>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dept_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("DeptId"));

                    b.Property<string>("Ancestors")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ancestors");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DelFlag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("del_flag");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("dept_name");

                    b.Property<string>("EmailValue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Leader")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("leader");

                    b.Property<int>("OrderNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("order_num");

                    b.Property<long>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("parent_id");

                    b.Property<string>("PhoneValue")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("DeptId");

                    b.ToTable("sys_dept", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysDictData", b =>
                {
                    b.Property<long>("DictCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dict_code");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("DictCode"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("CssClass")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("css_class");

                    b.Property<string>("DictLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dict_label");

                    b.Property<int>("DictSort")
                        .HasColumnType("int")
                        .HasColumnName("dict_sort");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dict_type");

                    b.Property<string>("DictValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dict_value");

                    b.Property<string>("IsDefault")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasColumnName("is_default");

                    b.Property<string>("ListClass")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("list_class");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("DictCode");

                    b.ToTable("sys_dict_data", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysDictType", b =>
                {
                    b.Property<long>("DictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dict_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("DictId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dict_name");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dict_type");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("DictId");

                    b.HasIndex("DictType")
                        .IsUnique();

                    b.ToTable("sys_dict_type", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysJob", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("JobId"));

                    b.Property<string>("Concurrent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("1")
                        .HasColumnName("concurrent");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("InvokeTarget")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("invoke_target");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("job_group");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("job_name");

                    b.Property<string>("MisfirePolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("3")
                        .HasColumnName("misfire_policy");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("JobId");

                    b.ToTable("sys_job", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysJobLog", b =>
                {
                    b.Property<long>("JobLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("JobLogId"));

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("ExceptionInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("exception_info");

                    b.Property<string>("InvokeTarget")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("invoke_target");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("job_group");

                    b.Property<string>("JobMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("job_message");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("job_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.HasKey("JobLogId");

                    b.ToTable("sys_job_log", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysLoginInfo", b =>
                {
                    b.Property<long>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("info_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InfoId"));

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("browser");

                    b.Property<string>("IpAddrValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ipaddr");

                    b.Property<string>("LoginLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_location");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_time");

                    b.Property<string>("Msg")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("msg");

                    b.Property<string>("Os")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("os");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("InfoId");

                    b.HasIndex("LoginTime");

                    b.HasIndex("Status");

                    b.ToTable("sys_logininfor", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysMenu", b =>
                {
                    b.Property<long>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MenuId"));

                    b.Property<string>("Component")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("component");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("icon");

                    b.Property<int>("IsCache")
                        .HasColumnType("int")
                        .HasColumnName("is_cache");

                    b.Property<int>("IsFrame")
                        .HasColumnType("int")
                        .HasColumnName("is_frame");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("menu_name");

                    b.Property<string>("MenuType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("C")
                        .HasColumnName("menu_type");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int")
                        .HasColumnName("order_num");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("path");

                    b.Property<string>("Perms")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("perms");

                    b.Property<string>("Query")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("query");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("RouteName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("route_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<string>("Visible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("visible");

                    b.HasKey("MenuId");

                    b.ToTable("sys_menu", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysNotice", b =>
                {
                    b.Property<int>("NoticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notice_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NoticeId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<byte[]>("NoticeContent")
                        .HasColumnType("longblob")
                        .HasColumnName("notice_content");

                    b.Property<string>("NoticeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notice_title");

                    b.Property<string>("NoticeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("1")
                        .HasColumnName("notice_type");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("NoticeId");

                    b.ToTable("sys_notice", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysOperLog", b =>
                {
                    b.Property<long>("OperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("oper_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OperId"));

                    b.Property<int>("BusinessType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("business_type");

                    b.Property<long>("CostTime")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_time");

                    b.Property<string>("DeptName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_name");

                    b.Property<string>("ErrorMsg")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("error_msg");

                    b.Property<string>("JsonResult")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("json_result");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("method");

                    b.Property<string>("OperIpValue")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("oper_ip");

                    b.Property<string>("OperLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("oper_location");

                    b.Property<string>("OperName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("oper_name");

                    b.Property<string>("OperParam")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("oper_param");

                    b.Property<DateTime?>("OperTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("oper_time");

                    b.Property<string>("OperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("oper_url");

                    b.Property<int>("OperatorType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("operator_type");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("request_method");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.HasKey("OperId");

                    b.HasIndex("BusinessType")
                        .HasDatabaseName("idx_sys_oper_log_business_type");

                    b.HasIndex("OperTime")
                        .HasDatabaseName("idx_sys_oper_log_oper_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sys_oper_log_status");

                    b.ToTable("sys_oper_log", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysPost", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PostId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("post_code");

                    b.Property<string>("PostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("post_name");

                    b.Property<int>("PostSort")
                        .HasColumnType("int")
                        .HasColumnName("post_sort");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("PostId");

                    b.ToTable("sys_post", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysRole", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DataScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("1")
                        .HasColumnName("data_scope");

                    b.Property<string>("DelFlag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("del_flag");

                    b.Property<bool>("DeptCheckStrictly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("dept_check_strictly");

                    b.Property<bool>("MenuCheckStrictly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("menu_check_strictly");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_key");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role_name");

                    b.Property<int>("RoleSort")
                        .HasColumnType("int")
                        .HasColumnName("role_sort");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.HasKey("RoleId");

                    b.ToTable("sys_role", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysRoleDept", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_id");

                    b.HasKey("RoleId", "DeptId");

                    b.HasIndex("DeptId");

                    b.ToTable("sys_role_dept", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysRoleMenu", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("sys_role_menu", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("avatar");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DelFlag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("del_flag");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_id");

                    b.Property<string>("EmailValue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LoginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_date");

                    b.Property<string>("LoginIpValue")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login_ip");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nick_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumberValue")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phonenumber");

                    b.Property<DateTime?>("PwdUpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pwd_update_date");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("2")
                        .HasColumnName("sex");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("00")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("sys_user", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUserOnline", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tokenId");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("browser");

                    b.Property<string>("IpAddrValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ipaddr");

                    b.Property<string>("LoginLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_location");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_time");

                    b.Property<string>("Os")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("os");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("TokenId");

                    b.ToTable("sys_user_online", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUserPost", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("sys_user_post", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_user_role", (string)null);
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysRoleDept", b =>
                {
                    b.HasOne("NetMVP.Domain.Entities.SysDept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMVP.Domain.Entities.SysRole", "Role")
                        .WithMany("RoleDepts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysRoleMenu", b =>
                {
                    b.HasOne("NetMVP.Domain.Entities.SysMenu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMVP.Domain.Entities.SysRole", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUserPost", b =>
                {
                    b.HasOne("NetMVP.Domain.Entities.SysPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMVP.Domain.Entities.SysUser", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUserRole", b =>
                {
                    b.HasOne("NetMVP.Domain.Entities.SysRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMVP.Domain.Entities.SysUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysRole", b =>
                {
                    b.Navigation("RoleDepts");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("NetMVP.Domain.Entities.SysUser", b =>
                {
                    b.Navigation("UserPosts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
